[package]
edition = "2021"
name = "nots-cli"
version = "0.1.0"

[dependencies]
clap = {version = "4.4.6", features = ["derive", "color"]}
color-eyre = "0.6"
inquire = "0.6.2"
time = "0.3"
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = "0.3"
