[workspace]
members = [
  "crates/notsd",
  "crates/nots-core",
  "crates/nots-cli",
  "crates/nots-worker",
  "crates/test-service",
]

resolver = "2"

[package]
name = "nots"
version = "0.1.0"

[lib]
path = "crates/nots-core/src/empty.rs"
