on:
  release:
    types: [created]

name: Build Binaries

permissions:
  contents: write

jobs:
  build-cli:
    name: Release ${{ github.ref }} ${{ matrix.platform.release_for }}
    if: startsWith(github.ref, 'refs/tags/nots-cli-')
    strategy:
      matrix:
        platform:
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: nots-cli.exe
            name: nots-cli-x86_64-pc-windows.zip

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: nots-cli
            name: nots-cli-x86_64-apple-darwin.tar.xz

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: nots-cli
            name: nots-cli-aarch64-apple-darwin.tar.xz

          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: nots-cli
            name: nots-cli-x86_64-unknown-linux.tar.xz

          - release_for: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: nots-cli
            name: nots-cli-aarch64-unknown-linux-musl.tar.xz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release --bin nots-cli"

      - name: .tar.xz if not Windows
        if: ${{ matrix.platform.release_for != 'Windows-x86_64' }}
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar -cJf ${{ matrix.platform.name }} nots-cli

      - name: .zip if Windows
        if: ${{ matrix.platform.release_for == 'Windows-x86_64' }}
        shell: powershell
        run: |
          cd target/${{ matrix.platform.target }}/release
          Compress-Archive -Path nots-cli.exe -DestinationPath ${{ matrix.platform.name }}

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
