on:
  release:
    types: [created]

jobs:
  build-cli:
    if: startsWith(github.ref, 'refs/tags/nots-cli-')
    strategy:
      matrix:
        platform:
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: nots.exe
            name: nots-cli-x86_64-pc-windows.zip

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: nots
            name: nots-cli-x86_64-apple-darwin.tar.gz

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: nots
            name: nots-cli-aarch64-apple-darwin.tar.gz

          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: nots
            name: nots-cli-x86_64-unknown-linux.tar.gz

          - release_for: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: nots
            name: nots-cli-aarch64-unknown-linux-musl.tar.gz

    runs-on: ${{ matrix.platform.os }}
    name: Release ${{ github.ref }} ${{ matrix.platform.release_for }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release --bin nots-cli"

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
