on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build and add binaries to (e.g. nots-cli-v0.1.0). Has to be a tag from a release."
        required: true
        type: string

name: Build and release binaries/containers

env:
  RELEASE_TAG_REF: ${{ github.event.inputs.tag || github.ref_name }}

jobs:
  build-notsd-docker:
    permissions:
      packages: write
    name: Release ${{ github.event.inputs.tag || github.ref_name }}
    if: "${{contains((github.event.inputs.tag || github.ref_name), 'notsd-v')}}"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.RELEASE_TAG_REF }}
      - name: Install latest stable Rust and add targets
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup toolchain install stable
          rustup default stable
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build binaries
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu --locked --bin notsd
          cargo build --release --target aarch64-unknown-linux-gnu --locked --bin notsd
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Outputs
        id: out
        run: |
          mkdir -p /tmp/outputs
          mv target/aarch64-unknown-linux-gnu/release/notsd /tmp/outputs/notsd-arm64
          mv target/x86_64-unknown-linux-gnu/release/notsd /tmp/outputs/notsd-amd64
          version=$(echo ${{ env.RELEASE_TAG_REF }} | sed 's/notsd-v//')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/explodingcamera/notsd:${{ steps.out.outputs.version }}
          platforms: linux/amd64,linux/arm64
          file: crates/notsd/Dockerfile
          context: /tmp/outputs
          build-args: |
            NOTS_VERSION=v${{ steps.out.outputs.version }}

  build-cli:
    permissions:
      contents: write
    name: Release ${{ github.event.inputs.tag || github.ref_name }} ${{ matrix.platform.release_for }}
    if: "${{contains((github.event.inputs.tag || github.ref_name), 'nots-cli-v')}}"
    strategy:
      matrix:
        platform:
          - release_for: Windows-x86_64
            os: ubuntu-22.04
            target: x86_64-pc-windows-gnu
            bin: nots-cli.exe
            name: nots-cli-x86_64-pc-windows.zip
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: nots-cli
            name: nots-cli-x86_64-apple-darwin.tar.xz
          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: nots-cli
            name: nots-cli-aarch64-apple-darwin.tar.xz
          - release_for: Linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
            bin: nots-cli
            name: nots-cli-x86_64-unknown-linux.tar.xz
          - release_for: Linux-aarch64
            os: ubuntu-22.04
            target: aarch64-unknown-linux-musl
            bin: nots-cli
            name: nots-cli-aarch64-unknown-linux-musl.tar.xz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.RELEASE_TAG_REF }}

      - name: Install latest stable Rust and add targets
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup target add ${{ matrix.platform.target }}

      - name: Install mingw-w64
        if: ${{ matrix.platform.release_for == 'Windows-x86_64' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Install aarch64 gcc
        if: ${{ matrix.platform.release_for == 'Linux-aarch64' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build binary
        run: cargo build --release --target ${{ matrix.platform.target }} --locked --bin nots-cli

      - name: .tar.xz if not Windows
        if: ${{ matrix.platform.release_for != 'Windows-x86_64' }}
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar -cJf ${{ matrix.platform.name }} nots-cli

      - name: .zip if Windows
        if: ${{ matrix.platform.release_for == 'Windows-x86_64' }}
        run: |
          cd target/${{ matrix.platform.target }}/release
          zip ${{ matrix.platform.name }} nots-cli.exe

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG_REF }}
          files: target/${{ matrix.platform.target }}/release/${{ matrix.platform.name }}
