on:
  push:
    paths:
      - "**.rs"
      - "Cargo.lock"

name: Test all crates

jobs:
  check:
    if: "${{!contains(github.event.head_commit.message , 'chore: release')}}"
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - uses: Swatinem/rust-cache@v2

      - name: Install latest stable Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Run cargo check
        run: cargo check --all --locked

      - name: Run cargo test
        run: cargo test --all --locked
