on:
  push:
    paths:
      - "**.rs"
      - "Cargo.lock"

name: Build & Test

jobs:
  check:
    if: "${{!contains(github.event.head_commit.message , 'chore: release')}}"
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install latest stable Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          rustflags: ""

      - uses: Swatinem/rust-cache@v2

      - name: Build debug binaries
        run: cargo build --all --locked

      - name: Run cargo check
        run: cargo check --all --locked

      - name: Run cargo test
        run: cargo test --all --locked
